### ISSUE TITLE
Support for other platforms?

### ISSUE THREAD

**Issue by frontierpsycho** [konsorten/go-xdelta#1]
I'm trying to use this on Linux and MacOS, but I see there's only a build script for Windows. Has it been tested on other platforms? Are there any plans to support Linux/MacOS?

If not, could you give pointers on how to add support?

Thanks.

**Comment by fkollmann** [comment]
Hi! Let me look into this. I had no experience with CGO previously, which changed over the last few months. I want to make sure the Windows and CGO implementation are as similar as possible. Please feel free to check back by the end of the week. Best Regards, Felix

**Comment by fkollmann** [comment]
Fixed in v0.2.0

**Comment by frontierpsycho** [comment]
Hey @fkollmann, that is fantastic, thank you so much!

One more thing, though: my issue on Linux (and Mac, but I'm guessing any Linux solution will be compatible with MacOS) is that I'm not sure how to build xdelta as an `.so` library. The regular xdelta build process seems to produce an executable alone. For Windows you had included the `build_windows.bat` script, on Linux, is there an easy way to build xdelta that I missed?

Again, thanks so much!

**Comment by fkollmann** [comment]
Hi, you don‘t need a native library on macOS and Linux. (I fixed the readme.) Best Regards, Felix

**Comment by frontierpsycho** [comment]
Alright, perfect, thanks!
